### ISSUE TITLE
Edit mode

### ISSUE THREAD

**Issue by notrajectory** [patrickchiang/obsidian-dialogue-mode#2]
Great plugin, loved using it! However, for a few hours I thought it was broken because as it turns out the colour change doesn't work for the edit mode. 
![uhh](https://github.com/user-attachments/assets/153e09e8-425d-46ef-85da-1001f1766a4b)
That's me being a little bit stupefied. I don't think it's a big or urgent issue as it works great in reading mode, just decided to leave a note in case you'd want to check it out. Thanks for the plugin!

**Comment by patrickchiang** [comment]
Ah, that's because the detection logic for regular quotes wasn't quite up to it (as opposed to my usage, which was mostly using the squiggly/smart quotes). I've fixed this issue now, including for single quotes, except it dumps apostrophes. 
Update to latest version (1.0.6) and you should see the fix. Hopefully it works for you, but if it doesn't, please let me know! Thanks for the report!

**Comment by notrajectory** [comment]
Yay it works! Thanks again!
